### ISSUE TITLE
new format for borghans

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#22]

**Comment by dweindl** [comment]
measurementData_Borghans_BiophysChem1997.tsv has comma as decimal separator

**Comment by yannikschaelte** [comment]
running the latest version of pypesto (0.0.4), there is by chance an error in pypesto.PetabImporter._check_parameter_mapping_ok, because 'observable_Ca' is not a column header in the dataframe created by ``amici.getDataObservablesAsDataFrame(model, [edata_for_condition])
``

I think this is bc in the borghans model's sbml file (https://github.com/LoosC/Benchmark-Models/tree/hackathon/hackathon_contributions_new_data_format/Borghans_BiophysChem1997) there is no name given for the observable id, so that https://github.com/ICB-DCM/AMICI/blob/master/python/amici/pandas.py#L259 fails. 

Question: What to do about this? We probably do not want to require obs names. Is there something wrong in the amici extraction? Would it be possible to always return ids in getDataObservablesAsDataFrame()?

**Comment by dweindl** [comment]
> Would it be possible to always return ids in getDataObservablesAsDataFrame()?

We could introduce a respective option I guess.

**Comment by yannikschaelte** [comment]
strange though somehow that the column header is literally blank:

```
         time datatype  t_presim            _std
0    0.029485     data       0.0 -0.457057   NaN
1    0.147621     data       0.0 -0.427785   NaN
2    0.312815     data       0.0 -0.463256   NaN
3    0.445615     data       0.0 -0.427268   NaN
4    0.566227     data       0.0 -0.466177   NaN
5    0.699263     data       0.0 -0.436278   NaN
6    0.724620     data       0.0 -0.093352   NaN
7    0.790627     data       0.0  0.000000   NaN
8    0.840515     data       0.0 -0.054564   NaN
9    0.922326     data       0.0 -0.145338   NaN
10   1.017975     data       0.0 -0.241524   NaN
```

**Comment by dweindl** [comment]
Blanks or really empty?

**Comment by yannikschaelte** [comment]
``""``, i.e. empty. Maybe the sbml parameter name is set to ``""`` somehow if it is not filled, and then extracted here?

**Comment by dweindl** [comment]
Can you report that in AMICI. If name is empty, ID should be used.

**Comment by yannikschaelte** [comment]
ok! an additional option to always use ids definitely makes sense to, since the toDataFrame function is now used in two cases in pypesto.

**Comment by yannikschaelte** [comment]
measurement file: measurement column should be not logged.

Although the column observableTransformation is log10, the measurements should be contained in lin scale, as the trafo will be applied later.

**Comment by yannikschaelte** [comment]
to specify: I guess it was log10'ed, not log'ed.
